name: Despliegue de Angular a Desarrollo (Firebase Hosting)

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Generate .env File
        run: echo ${{ vars.DOTENV }} > .env

      - name: Install dependencies
        run: npm install

      - name: Set up config environments
        run: npm run config

      - name: Build project
        run: npm run build

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy --token $FIREBASE_TOKEN