name: Despliegue de Angular a Producción (cPanel)

on:
  push:
    branches:
      - main
    # tags:
    #   - '**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3.3.0

    - name: Install Node.js
      uses: actions/setup-node@v2.1.5
      with:
        node-version: '18.14.0'

    - name: Generate .env File
      run: echo ${{ secrets.DOTENV }} > .env

    - name: Install dependencies
      run: npm install

    - name: Set up config environments
      run: |
        npm run config
        ls -l
        echo ${GITHUB_WORKSPACE}

    - name: Build project
      run: npm run build

    - name: Upload files to cPanel
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.CPANEL_HOSTNAME }}
        username: ${{ secrets.CPANEL_USERNAME }}
        key: ${{ secrets.CPANEL_SSH_KEY }}
        passphrase: ${{ secrets.CPANEL_SSH_PASSPHRASE }}
        target: ${{ vars.CPANEL_PATH }}
        source: dist/fitness-trainer/*
        strip_components: 2
        rm: true