name: Despliegue de Angular a cPanel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2.3.4

    - name: Install Node.js
      uses: actions/setup-node@v2.1.5
      with:
        node-version: '18.14.0'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Upload files to cPanel
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.CPANEL_HOSTNAME }}
        username: ${{ secrets.CPANEL_USERNAME }}
        key: ${{ secrets.CPANEL_SSH_KEY }} # Base64
        passphrase: ${{ secrets.CPANEL_SSH_PASSPHRASE }}
        source: dist/fitness-trainer/*
        target: ${{ vars.CPANEL_PATH }}
        strip_components: 2
        rm: true