name: Despliegue de Angular a Desarrollo (Firebase Hosting)

on:
  push:
    branches:
      - dev
    tags:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Build project
        env:
          DOTENV: ${{ vars.DOTENV_DEV }}
        run: |
          echo $DOTENV > .env
          npm install
          npm run config
          npm run build

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy --token $FIREBASE_TOKEN