name: Despliegue de Angular a cPanel

on:
  push:
    branches:
      - main # Nombre de la rama que deseas monitorear

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2.3.4

    - name: Install Node.js
      uses: actions/setup-node@v2.1.5
      with:
        node-version: '18.14.0'

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Deploy Project
      run: npm run deploy