name: Despliegue de Angular a Desarrollo (Firebase Hosting)

on:
  workflow_dispatch:
#   push:
#     tags:
#       - '**'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - name: Install Project
        run: npm install

      - name: Build project
        run: npm run build

      - name: Archive Build
        uses: actions/upload-artifact@v3
        with:
          path: |
            dist/fitness-trainer
            firebase.json

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Download Build
        uses: actions/download-artifact@v3
        with:
          path: .

      - name: Mostrar contenido del directorio
        run: ls

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --token $FIREBASE_TOKEN